{
  "name": "EcoGrow Co.",
  "version": "1.0.0",
  "author": "EcoGrow Co.",
  "shopify_feature": "1.0",
  "theme_name": "EcoGrow Co.",
  "theme_id": "ecoGrowCo_1_0",
  "target": "store",
  "role": "main"
}